import { Championship } from './types'

export const MOCK_CHAMPIONSHIPS: Championship[] = [
  {
    id: 'demo-1',
    name: 'FLY Creators — Abril 2026',
    description: 'O maior campeonato de criação de conteúdo da FLY Media. Três objetivos, premiação total de R$ 7.500.',
    coverGradient: 'linear-gradient(160deg, #0a1a00 0%, #1a3d00 40%, #000 100%)',
    startDate: '2026-04-01',
    endDate: '2026-04-30',
    rankingDate: '2026-05-01',
    paymentDeadline: '2026-05-07',
    mainObjectiveDescription: 'Ranking de Views',
    mainObjectiveType: 'direct',
    mainObjectiveMetric: 'views_totais',
    mainPositions: [
      { place: 1, prize: 2000 },
      { place: 2, prize: 1200 },
      { place: 3, prize: 800 },
      { place: 4, prize: 400 },
      { place: 5, prize: 200 },
    ],
    mainVideoReviews: [],
    secondaryObjectives: [
      {
        id: 'obj-direct-1',
        description: 'Melhor Vídeo Único',
        details: 'Participante com o vídeo de maior audiência isolada no período.',
        type: 'direct',
        metric: 'melhor_video',
        positions: [
          { place: 1, prize: 500 },
          { place: 2, prize: 300 },
          { place: 3, prize: 200 },
        ],
      },
      {
        id: 'obj-subj-1',
        description: 'Melhor Edição',
        details: 'Avaliação subjetiva da qualidade de edição dos vídeos. O administrador revisa e atribui as posições.',
        type: 'subjective',
        positions: [
          { place: 1, prize: 500 },
          { place: 2, prize: 300 },
          { place: 3, prize: 100 },
        ],
        videoReviews: [
          { videoId: 'v1', participantId: 'p1', place: 2 },
          { videoId: 'v3', participantId: 'p3', place: 1 },
          { videoId: 'v5', participantId: 'p5', place: 3 },
          { videoId: 'v7', participantId: 'p7', place: null },
          { videoId: 'v9', participantId: 'p9', place: null },
        ],
      },
    ],
    validContent: [
      { title: 'Reels, TikToks e Shorts com até 3 minutos de duração' },
      { title: 'Obrigatório usar #FLYCreators e #FlyMedia na legenda' },
      { title: 'Apenas vídeos publicados entre 01/04 e 30/04/2026' },
      { title: 'Regulamento completo', url: 'https://docs.google.com/document/d/fly-creators-abril-2026' },
    ],
    rules: [
      { text: 'Plataformas liberadas: TikTok, Instagram Reels e YouTube Shorts.' },
      { text: 'Cada participante deve ter suas contas cadastradas antes de postar.' },
      { text: 'Views de anúncios pagos não são contabilizadas.' },
      { text: 'Vídeos com menos de 10 segundos de conteúdo do Eagle não são válidos.' },
      { text: 'O administrador tem autonomia de desclassificar participantes que usarem bots.' },
      { text: 'Regulamento completo disponível no link.', url: 'https://docs.google.com/document/d/fly-creators-abril-2026' },
    ],
    paymentInfo: 'Pagamentos via Pix até 7 dias após a divulgação do resultado.\nChave Pix: pagamentos@flymedia.com.br',
    participants: [
      { id: 'p1', name: 'Gabriel Mendes', handle: '@gabmendes_edits' },
      { id: 'p2', name: 'Lucas Ferreira', handle: '@lucasf.create' },
      { id: 'p3', name: 'Ana Paula Costa', handle: '@anapaulacosta' },
      { id: 'p4', name: 'Rodrigo Alves', handle: '@ralves.clips' },
      { id: 'p5', name: 'Beatriz Lima', handle: '@belimalima' },
      { id: 'p6', name: 'Felipe Santos', handle: '@felipesantos.edits' },
      { id: 'p7', name: 'Mariana Souza', handle: '@mari.souza.fly' },
      { id: 'p8', name: 'Thiago Nunes', handle: '@thiagonu' },
      { id: 'p9', name: 'Camila Reis', handle: '@camilareis.vfx' },
      { id: 'p10', name: 'Diego Oliveira', handle: '@diegooliveira' },
    ],
    videos: [
      { id: 'v1', participantId: 'p1', title: 'Eagle Trindade — Montage Fire Cuts', views: 142000, postedAt: '2026-04-03', platform: 'instagram', url: 'https://www.instagram.com/reel/C9aAbCdEfGh/' },
      { id: 'v2', participantId: 'p1', title: 'FLY Edits Vol.2 — Best Moments', views: 89000, postedAt: '2026-04-10', platform: 'tiktok', url: 'https://www.tiktok.com/@gabmendes_edits/video/7380001234567' },
      { id: 'v3', participantId: 'p3', title: 'Cinematic FLY Highlights', views: 210000, postedAt: '2026-04-04', platform: 'youtube', url: 'https://www.youtube.com/shorts/FlyHL_Apr04' },
      { id: 'v4', participantId: 'p3', title: 'FLY Night Edition', views: 134000, postedAt: '2026-04-12', platform: 'instagram', url: 'https://www.instagram.com/reel/C9bBcDeFgHi/' },
      { id: 'v5', participantId: 'p5', title: 'Beat Sync FLY — Trap Edit', views: 175000, postedAt: '2026-04-05', platform: 'tiktok', url: 'https://www.tiktok.com/@belimalima/video/7380002345678' },
      { id: 'v6', participantId: 'p6', title: 'Color Grade Tutorial FLY', views: 63000, postedAt: '2026-04-07', platform: 'youtube', url: 'https://www.youtube.com/shorts/FlyTut_Apr07' },
      { id: 'v7', participantId: 'p7', title: 'FLY VFX Breakdown', views: 121000, postedAt: '2026-04-08', platform: 'instagram', url: 'https://www.instagram.com/reel/C9cCdEfGhIj/' },
      { id: 'v8', participantId: 'p8', title: 'Lifestyle Montage FLY', views: 94000, postedAt: '2026-04-09', platform: 'tiktok', url: 'https://www.tiktok.com/@thiagonu/video/7380003456789' },
      { id: 'v9', participantId: 'p9', title: 'FLY After Effects Edit', views: 188000, postedAt: '2026-04-11', platform: 'youtube', url: 'https://www.youtube.com/shorts/FlyAE_Apr11' },
      { id: 'v10', participantId: 'p10', title: 'FLY Compilation — Abril', views: 156000, postedAt: '2026-04-13', platform: 'instagram', url: 'https://www.instagram.com/reel/C9dDeFgHiJk/' },
      { id: 'v11', participantId: 'p2', title: 'FLY Transition Pack Edit', views: 98500, postedAt: '2026-04-06', platform: 'tiktok', url: 'https://www.tiktok.com/@lucasf.create/video/7380004567890' },
      { id: 'v12', participantId: 'p4', title: 'FLY Slow Motion Vibes', views: 87200, postedAt: '2026-04-14', platform: 'instagram', url: 'https://www.instagram.com/reel/C9eEfGhIjKl/' },
    ],
    ranking: [],
    status: 'active',
  },
  {
    id: 'demo-2',
    name: 'FLY Sprint — Maio 2026',
    description: 'Campeonato relâmpago de 10 dias focado no melhor vídeo único.',
    coverGradient: 'linear-gradient(160deg, #1a0533 0%, #3d0070 40%, #000 100%)',
    startDate: '2026-05-01',
    endDate: '2026-05-10',
    mainObjectiveDescription: 'Melhor Vídeo',
    mainObjectiveType: 'direct',
    mainObjectiveMetric: 'melhor_video',
    mainPositions: [
      { place: 1, prize: 1500 },
      { place: 2, prize: 800 },
      { place: 3, prize: 500 },
    ],
    mainVideoReviews: [],
    secondaryObjectives: [
      {
        id: 'obj-sprint-subj',
        description: 'Criatividade',
        details: 'Avaliação do conceito criativo do vídeo pelo administrador.',
        type: 'subjective',
        positions: [
          { place: 1, prize: 300 },
          { place: 2, prize: 200 },
        ],
        videoReviews: [],
      },
    ],
    validContent: [
      { title: 'Qualquer formato de vídeo curto (até 60 segundos)' },
      { title: 'Obrigatório usar #FLYSprint na legenda' },
    ],
    rules: [
      { text: 'Apenas 1 vídeo por participante será contabilizado (o de melhor desempenho).' },
      { text: 'Plataformas: TikTok, Instagram ou YouTube Shorts.' },
    ],
    participants: [
      { id: 'sp1', name: 'João Camargo', handle: '@joaocamargo' },
      { id: 'sp2', name: 'Felipe Oliveira', handle: '@felipeoliveira' },
      { id: 'sp3', name: 'Lucas Mendes', handle: '@lucasmendes' },
      { id: 'sp4', name: 'Mariana Ribeiro', handle: '@marianaribeiro' },
      { id: 'sp5', name: 'Thiago Rodrigues', handle: '@thiagorodrigues' },
    ],
    videos: [],
    ranking: [],
    status: 'upcoming',
  },
]
